### DISCUSSION TITLE
Is there a way to have unformatted partition?

### DISCUSSION THREAD

**Discussion by budimanjojo** [siderolabs/sidero#781] [Q&A] [answered]
Hello, I want to migrate my current cluster to talos with sidero as the node manager. As all my nodes only have a single SSD, I want to give rook ceph an unformatted 30GB partition. Is there a way to get this with sidero? I looked at the doc https://www.talos.dev/docs/v0.13/reference/configuration/#machinedisk and I'm thinking I should be able to do this? I'm not sure
```
- device: /dev/sda
  # A list of partitions to create on the disk.
  partitions:
    - size: 30 GB
```
My expected result will be having a `/dev/sda` (assuming a 120GB SSD) with 80GB as rootfs partition and 30GB unformatted partition.
Thanks before
