### ISSUE TITLE
specified install disk does not exist ""

### ISSUE THREAD

**Issue by japtain-cack** [siderolabs/sidero#1101]
I have specified the install disk as `/dev/nvme0n1` but I'm getting a disk does not exist error, on provisioning of a bare metal system. I have confirmed that during the initial boot, the dmesg displays `Fast wiped /dev/nvme0n1`, and `Wipe complete`. So `/dev/nvme0n1` should be the correct disk.

I believe the issue is that the serverclass `talos-masters` is the only one being applied as it's the only one defined in the `talos-cp` `MetalMachineTemplate` and referenced by the `TalosControlPlane`'s `infrastructureTemplate`.

How do ServerClasses get applied? Does any matching serverclass contribute to the configuration of the matched server? How can I have a `talos-masters` serverclass and supply install disks, or other configPatches, conditionally based on hardware type/version/etc?

As you can see below, I have defined a talos-masters serverclass which is referenced by the cluster. You can only set one infrastructureTemplate on the TalosControlPlane to my knowledge. If you look at my serverclasses, you can see that the `talos-lenovo-m710q` serverclass defines the install disk and is matched according to the describe serverclasses below.

# Resources
## kubectl get serverclasses
```
NAME                    AVAILABLE   IN USE                                                                                                                   AGE
any                     []          ["0778b200-9684-11e8-8f88-e0e722df6d00","b80c6841-fb72-4fa2-9fec-7bc8eb7faab3","f2f49248-b3c3-4403-9207-a819bfc86b49"]   6d16h
talos-lenovo-m710q      []          ["0778b200-9684-11e8-8f88-e0e722df6d00"]                                                                                 155m
talos-masters           []          ["0778b200-9684-11e8-8f88-e0e722df6d00","b80c6841-fb72-4fa2-9fec-7bc8eb7faab3","f2f49248-b3c3-4403-9207-a819bfc86b49"]   6d16h
talos-virtual-esx       []          []                                                                                                                       155m
talos-virtual-proxmox   []          ["b80c6841-fb72-4fa2-9fec-7bc8eb7faab3","f2f49248-b3c3-4403-9207-a819bfc86b49"]                                          155m
talos-workers           []          []                                                                                                                       6d16h
```

## kubectl describe metalmachine talos-cp-hl729
```
Name:         talos-cp-hl729
Namespace:    sidero-system
Labels:       cluster.x-k8s.io/cluster-name=talos
Annotations:  cluster.x-k8s.io/cloned-from-groupkind: MetalMachineTemplate.infrastructure.cluster.x-k8s.io
              cluster.x-k8s.io/cloned-from-name: talos-cp
API Version:  infrastructure.cluster.x-k8s.io/v1alpha3
Kind:         MetalMachine
Metadata:
  Creation Timestamp:  2023-04-08T21:16:28Z
  Finalizers:
    metalmachine.infrastructure.cluster.x-k8s.io
  Generation:  2
  Managed Fields:
    API Version:  infrastructure.cluster.x-k8s.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:cluster.x-k8s.io/cloned-from-groupkind:
          f:cluster.x-k8s.io/cloned-from-name:
        f:finalizers:
          .:
          v:"metalmachine.infrastructure.cluster.x-k8s.io":
        f:labels:
          .:
          f:cluster.x-k8s.io/cluster-name:
        f:ownerReferences:
          .:
          k:{"uid":"f2c55399-28af-4b93-8647-659ca4912202"}:
      f:spec:
        .:
        f:providerID:
        f:serverClassRef:
        f:serverRef:
    Manager:      manager
    Operation:    Update
    Time:         2023-04-08T21:22:08Z
    API Version:  infrastructure.cluster.x-k8s.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:addresses:
        f:conditions:
        f:ready:
    Manager:      manager
    Operation:    Update
    Subresource:  status
    Time:         2023-04-08T21:23:06Z
  Owner References:
    API Version:           cluster.x-k8s.io/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Machine
    Name:                  talos-cp-2f46r
    UID:                   f2c55399-28af-4b93-8647-659ca4912202
  Resource Version:        2429599
  UID:                     bb708684-3858-4f8b-a127-bb27a7dc3d9d
Spec:
  Provider ID:  sidero://0778b200-9684-11e8-8f88-e0e722df6d00
  Server Class Ref:
    API Version:  metal.sidero.dev/v1alpha1
    Kind:         ServerClass
    Name:         talos-masters
  Server Ref:
    Kind:  Server
    Name:  0778b200-9684-11e8-8f88-e0e722df6d00
Status:
  Addresses:
    Address:  master-03
    Type:     Hostname
  Conditions:
    Last Transition Time:  2023-04-08T21:22:08Z
    Message:               no matching nodes found
    Reason:                ProviderUpdateFailed
    Severity:              Warning
    Status:                False
    Type:                  ProviderSet
    Last Transition Time:  2023-04-08T21:23:06Z
    Message:               failed to validate config: 2 errors occurred:
                           * an install disk is required in "metal" mode
                           * specified install disk does not exist: ""


    Reason:    TalosConfigLoadFailed
    Severity:  Error
    Status:    False
    Type:      TalosConfigLoaded
  Ready:       true
Events:        <none>
```

## ServerClasses
```
### sidero/kustomize/serverClasses.yaml ###
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: talos-virtual-proxmox
  namespace: default
spec:
  qualifiers:
    systemInformation:
      - manufacturer: QEMU
        version: pc-i440fx-6.2
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sda
  bootFromDiskMethod: ipxe-exit
---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: talos-virtual-esx
  namespace: default
spec:
  qualifiers:
    systemInformation:
      - manufacturer: VMware, Inc.
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sda
  bootFromDiskMethod: ipxe-exit
---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: talos-lenovo-m710q
  namespace: default
spec:
  qualifiers:
    systemInformation:
      - manufacturer: LENOVO
        version: ThinkCentre M710q
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/nvme0n1
  bootFromDiskMethod: ipxe-exit
---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: talos-masters
  namespace: default
spec:
  selector:
    matchLabels:
      node-role.kubernetes.io/control-plane: "true"
  qualifiers:
    systemInformation:
      - manufacturer: VMware, Inc.
      - manufacturer: QEMU
      - manufacturer: LENOVO
        family: ThinkCentre M710q
  bootFromDiskMethod: ipxe-exit
---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: talos-workers
  namespace: default
spec:
  selector:
    matchLabels:
      node-role.kubernetes.io/worker: "true"
  qualifiers:
    systemInformation:
      - manufacturer: VMware, Inc.
      - manufacturer: QEMU
      - manufacturer: LENOVO
        family: ThinkCentre M710q
  bootFromDiskMethod: ipxe-exit
```

## Talos Cluster
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: talos
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.10.0.0/16
    services:
      cidrBlocks:
      - 10.11.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: talos-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalCluster
    name: talos
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalCluster
metadata:
  name: talos
  namespace: default
spec:
  controlPlaneEndpoint:
    host: cp.talos.example.com
    port: 6443
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalMachineTemplate
metadata:
  name: talos-cp
  namespace: default
spec:
  template:
    spec:
      serverClassRef:
        apiVersion: metal.sidero.dev/v1alpha1
        kind: ServerClass
        name: talos-masters
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: talos-cp
  namespace: default
spec:
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.3.6
      configPatches:
      - op: add
        path: /machine/network
        value:
          interfaces:
          - interface: eth0
            dhcp: true
            vip:
              ip: 10.100.50.52
      - op: add
        path: /machine/certSANs/-
        value:
          "*.talos.example.com"
      - op: add
        path: /cluster/apiServer/certSANs/-
        value:
          "*.talos.example.com"
      - op: add
        path: /machine/kubelet
        value:
          extraArgs:
            rotate-server-certificates: true
      - op: add
        path: /machine/install/extensions
        value:
          - image: ghcr.io/siderolabs/drbd:9.2.0-v1.3.6
      - op: add
        path: /machine/kernel
        value:
          modules:
          - name: drbd
          - name: drbd_transport_tcp
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalMachineTemplate
    name: talos-cp
  replicas: 3
  version: v1.26.2
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: talos-workers
  namespace: default
spec:
  template:
    spec:
      generateType: join
      talosVersion: v1.3.6
      configPatches:
      - op: add
        path: /machine/kubelet
        value:
          extraArgs:
            rotate-server-certificates: true
      - op: add
        path: /machine/install/extensions
        value:
          - image: ghcr.io/siderolabs/drbd:9.2.0-v1.3.6
      - op: add
        path: /machine/kernel
        value:
          modules:
          - name: drbd
          - name: drbd_transport_tcp
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: talos-workers
  namespace: default
spec:
  clusterName: talos
  replicas: 0
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: talos-workers
      clusterName: talos
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: MetalMachineTemplate
        name: talos-workers
      version: v1.26.2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalMachineTemplate
metadata:
  name: talos-workers
  namespace: default
spec:
  template:
    spec:
      serverClassRef:
        apiVersion: metal.sidero.dev/v1alpha1
        kind: ServerClass
        name: talos-workers
```

**Comment by japtain-cack** [comment]
I also noticed that the `talosVersion` in the `TalosControlPlane` is not respected. I've installed 3 nodes so far, and each one shows version `v1.3.0`. I had to upgrade each node manually.

**Comment by japtain-cack** [comment]
I was going through the documentation again and noticed this page, https://www.sidero.dev/v0.5/resource-configuration/metadata/. How can we specify conditional patches, based on differences in hardware, for a StorageClass?

**Comment by japtain-cack** [comment]
Also, outside of the basic setup, there seems to be no production oriented deployment documentation. It would be useful for those of us that are evaluating this for professional reasons to have documentation oriented for a production ready deployment, with recommended hardening procedures and the like.

**Comment by japtain-cack** [comment]
I think the easiest solution that comes to mind is, being able to select multiple ServerClasses when defining the MetalMachineTemplate. Possibly using a ServerClass label, that exists on multiple ServerClasses, or something similar. That way you can have various ServerClasses, with a mixture of hardware and install disk configurations, and it could pull from any of the StorageClasses with the common label.

**Comment by smira** [comment]
There are many questions in this issue, so not sure if the original problem is still relevant? 

The server class the server was picked from can be seen in `ServerBinding` resource once the server is allocated.

As install disk is _usually_ specific to the node, it might make sense to make it `Server`-level. If you have many similar machines, you can use `ServerClass` to provide specific patches.

Also please keep in mind Talos allows picking up system disk using disk selectors: https://www.talos.dev/v1.3/reference/configuration/#installconfig

**Comment by smira** [comment]
Just in case, you can have multiple worker machine deployments for a single cluster this way you could have multiple worker sets coming from multiple ServerClasses. You can also use that to e.g. label them different way.

`Server`-level patching should work as well, as long as you can automate it. The whole idea of CAPI is that it is extensible - you can build a controller which ensures each `Server` has proper config patches based on the hardware info in the resource, or some external inventory database you might have.

**Comment by japtain-cack** [comment]
Hmm, after looking through all the resources again, I think I might have a potential solution. I may be able to duplicate the below resources for each set of hardware. Not exactly ideal, a lot of code duplication, but this may be a viable solution. This is just a thought so far, I haven't tested anything and won't be able to for a couple of days.

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: talos-workers-arm
  namespace: default
spec:
  clusterName: talos
  replicas: 0
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: talos-workers
      clusterName: talos
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: MetalMachineTemplate
        name: talos-workers-arm
      version: v1.26.2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalMachineTemplate
metadata:
  name: talos-workers-arm
  namespace: default
spec:
  template:
    spec:
      serverClassRef:
        apiVersion: metal.sidero.dev/v1alpha1
        kind: ServerClass
        name: talos-workers-arm
```
