### ISSUE TITLE
iflinkwait: command not found

### ISSUE THREAD

**Issue by kubebn** [siderolabs/sidero#1123]
DHCP configuration:

```
subnet 10.1.1.0 netmask 255.255.255.0 {
   authoritative;
   range 10.1.1.50 10.1.1.180;
   default-lease-time 3600;
   get-lease-hostnames true;
   max-lease-time 3600;
   option subnet-mask 255.255.255.0;
   option broadcast-address 10.1.1.250;
   option routers 10.1.1.1;
   option domain-name-servers 1.1.1.1, 1.0.0.1;
   option domain-name "weecodelab.nl";
   include "/etc/dhcp/ipxe-metal.conf";
}

cat /etc/dhcp/ipxe-metal.conf
allow bootp;
allow booting;

# IP address for PXE-based TFTP methods
next-server 10.1.1.30;

# Configuration for iPXE clients
class "ipxeclient" {
  match if exists user-class and (option user-class = "iPXE");
  filename "http://10.1.1.30:8081/boot.ipxe";
}

# Configuration for legacy BIOS-based PXE boot
class "biosclients" {
  match if not exists user-class and substring (option vendor-class-identifier, 15, 5) ;
  filename "undionly.kpxe";
}

# Configuration for UEFI-based PXE boot
class "pxeclients" {
  match if not exists user-class and substring (option vendor-class-identifier, 0, 9) =;
  filename "ipxe.efi";
}

# Configuration for UEFI-based HTTP boot
class "httpclients" {
  match if not exists user-class and substring (option vendor-class-identifier, 0, 10) ;
  option vendor-class-identifier "HTTPClient";
  filename "http://10.1.1.30:8081/tftp/ipxe.efi";
}
```
Sidero installation:

```
export SIDERO_CONTROLLER_MANAGER_HOST_NETWORK=false
export SIDERO_CONTROLLER_MANAGER_API_ENDPOINT=10.1.1.30
export SIDERO_CONTROLLER_MANAGER_SIDEROLINK_ENDPOINT=10.1.1.30
clusterctl init -b talos -c talos -i sidero
```
MetalLB configuration:

```
kind: Service
apiVersion: v1
metadata:
  name: sidero-udp
  namespace: sidero-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "sidero"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.1.30
  selector:
    app: sidero
  ports:
    - name: tftp
      targetPort: tftp
      protocol: UDP
      port: 69
    - name: siderolink
      targetPort: siderolink
      protocol: UDP
      port: 51821
---
apiVersion: v1
kind: Service
metadata:
  name: sidero-tcp
  namespace: sidero-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "sidero"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.1.30
  selector:
    app: sidero
  ports:
  - port: 8081
    name: http
    protocol: TCP
    targetPort: http
```

Exposed services check:
```
~ ❯ curl -I http://10.1.1.30:8081/tftp/ipxe.efi
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 1047552
Content-Type: application/octet-stream
Last-Modified: Fri, 05 May 2023 19:12:19 GMT
Date: Fri, 05 May 2023 19:57:21 GMT

~ ❯ curl -I http://10.1.1.30:8081/boot.ipxe
HTTP/1.1 200 OK
Date: Fri, 05 May 2023 19:57:27 GMT
Content-Length: 967
Content-Type: text/plain; charset=utf-8
```
Pods:
```
~ ❯ k get po -n cabpt-system
NAME                                       READY   STATUS    RESTARTS   AGE
cabpt-controller-manager-bcbb75fd8-k9srf   1/1     Running   0          46m
~ ❯ k get po -n cacppt-system
NAME                                         READY   STATUS    RESTARTS   AGE
cacppt-controller-manager-5b99d8794f-gnbsc   1/1     Running   0          46m
~ ❯ k get po -n capi-system
NAME                                       READY   STATUS    RESTARTS   AGE
capi-controller-manager-86c6bfd9b5-b4ctj   1/1     Running   0          46m
~ ❯ k get po -n sidero-system
NAME                                         READY   STATUS    RESTARTS   AGE
caps-controller-manager-5b4b95bcdb-xrhcx     1/1     Running   0          46m
sidero-controller-manager-7d5b96cf6d-lm7tm   4/4     Running   0          46m
```

Starting a VM in Proxmox, which actually worked before and ipxe is failing with the following:
```
SeaBIOS (version rel-1.16.1-0-g3208b098f51a-prebuilt.qemu.org)
Machine UUID 1bae3ef9-2dd0-4441-847f-8e33100ad0cf


iPXE (http://ipxe.org) 00:12.0 C000 PCI2.10 PnP PMM+7EFD0C80+7EF30C80 C000




Press ESC for boot menu.

Booting from Hard Disk...
Boot failed: not a bootable disk

Booting from DVD/CD...
Boot failed: Could not read from CDROM (code 0003)
Booting from ROM...
iPXE (PCI 00:12.0) starting execution...ok
iPXE initialising devices...ok



iPXE 1.20.1+ (g4bd0) -- Open Source Network Boot Firmware -- http://ipxe.org
Features: DNS HTTP iSCSI TFTP AoE ELF MBOOT PXE bzImage Menu PXEXT

net0: 2e:9e:75:f6:51:87 using 82540em on 0000:00:12.0 (open)
  [Link:up, TX:0 TXE:0 RX:0 RXE:0]
Configuring (net0 2e:9e:75:f6:51:87)...... ok
net0: 10.1.1.65/255.255.255.0 gw 10.1.1.1
Next server: 10.1.1.30
Filename: http://10.1.1.30:8081/boot.ipxe
http://10.1.1.30:8081/boot.ipxe... ok
boot.ipxe : 967 bytes [script]
net0: 2e:9e:75:f6:51:87 using 82540em on 0000:00:12.0 (open)
  [Link:up, TX:8 TXE:0 RX:13 RXE:6]
  [RXE: 6 x "The socket is not connected (http://ipxe.org/380a6001)"]
iflinkwait: command not found

Failed to iPXE boot successfully via all interfaces
Retrying...

iflinkwait: command not found

Failed to iPXE boot successfully via all interfaces
Retrying...

iflinkwait: command not found

Failed to iPXE boot successfully via all interfaces
Retrying...

iflinkwait: command not found

Failed to iPXE boot successfully via all interfaces
Retrying...

iflinkwait: command not found

Failed to iPXE boot successfully via all interfaces
Retrying...

iflinkwait: command not found

Failed to iPXE boot successfully via all interfaces
Retrying...

iflinkwait: command not found

Failed to iPXE boot successfully via all interfaces
Retrying...

iflinkwait: command not found

Failed to iPXE boot successfully via all interfaces
Retrying...

iflinkwait: command not found

Failed to iPXE boot successfully via all interfaces
Retrying...

iflinkwait: command not found

Failed to iPXE boot successfully via all interfaces
Retrying...

iflinkwait: command not found

Failed to iPXE boot successfully via all interfaces

Failed to get a valid response after 10 attempts
```
