### ISSUE TITLE
Provide a way to make single node clusters schedulable

### ISSUE THREAD

**Issue by lieberlois** [siderolabs/sidero#1219]
By default, sidero provisioned control plane nodes will have the NoSchedule taint. In the documentation, I have found nothing to reconfigure that. Its possible to configure that for Talos (https://www.talos.dev/v1.5/talos-guides/howto/workers-on-controlplane/) but I havent found anything regarding the sidero clusterapi provider.

**Comment by smira** [comment]
Just apply a config patch from the doc you referenced in Sidero Metal. Any Talos machine config change should be a config patch in Sidero/CAPI.

**Comment by smira** [comment]
yes, controlplane makes sense

**Comment by lieberlois** [comment]
So that configPatch should work?

```yaml
configPatches:
    - op: replace
      path: /cluster/allowSchedulingOnControlPlanes
      value: true
```
