### ISSUE TITLE
Documentation for exposing Sidero services is light

### ISSUE THREAD

**Issue by hyperbolic2346** [siderolabs/sidero#1236]
The [documentation](https://github.com/siderolabs/sidero/blob/main/website/content/v0.6/Getting%20Started/expose-services.md) for exposing Sidero services is lacking when not using the default host networking. There is talk about using metallb, but no information on how to get Sidero to create loadbalancer services. There is also no information regarding `export SIDERO_CONTROLLER_MANAGER_HOST_NETWORK=true` and other options on the installing page. The Cluster API linked on that page has no mention of Sidero or environment variables.

Outstanding questions:
- Do I edit the services with `kubectl edit` and change the type?
- What other environment variables could be interesting when calling `clusterctl`
- Is there a way for someone to edit the values used for `SIDERO_CONTROLLER_MANAGER_API_ENDPOINT` and `SIDERO_CONTROLLER_MANAGER_SIDEROLINK_ENDPOINT`? Are they stored in a configmap somewhere? There is no mention of these needing to match the upcoming load balanced IP addresses until after they are used.

**Comment by johanjk** [comment]
All clusterctl env variables are listed here [here](https://www.sidero.dev/v0.6/overview/installation/)

Sidero itself is installed using a kustomization, it can be found [here](https://github.com/siderolabs/sidero/blob/main/config/kustomization.yaml). It does not create `LoadBalancer` services.

Assuming you have [metallb](https://metallb.universe.tf/installation/) and [externaldns](https://github.com/kubernetes-sigs/external-dns) correctly configured, you can either edit the services (as you suggested), or create additional services, leaving the internal sidero service alone.

eg. for the `tftp` service: _(you would need similar for `http` and `siderolink`)_
```yaml
apiVersion: v1
kind: Service
metadata:
  name: sidero-tftp-metallb
  namespace: sidero-system
  annotations:
    metallb.universe.tf/loadBalancerIPs: <static_ip>
    metallb.universe.tf/allow-shared-ip: "<share_key>"
    external-dns.alpha.kubernetes.io/hostname: "<dnsname>"
spec:
  ports:
  - protocol: UDP
    port: 69
    targetPort: tftp
  selector:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    cluster.x-k8s.io/v1alpha4: v1alpha3
    cluster.x-k8s.io/v1beta1: v1alpha3
    control-plane: sidero-controller-manager
  type: LoadBalancer
  externalTrafficPolicy: Cluster
```
