### ISSUE TITLE
pre-defined providers of clusterctl still reference old talos-systems GitHub organization

### ISSUE THREAD

**Issue by sauterp** [siderolabs/sidero#819]
I created a local kubernetes cluster in docker with talosctl and installed clusterctl 1.1.3.

When I try to install sidero:

`clusterctl init -b talos -c talos -i sidero --target-namespace default`

I get

```
Fetching providers
Error: invalid provider metadata: version v0.5.3 for the provider default/bootstrap-talos does not match any release series
```
I noticed that

`clusterctl config repositories`

still refers to the old GitHub organization talos-systems instead of siderolabs. Here the output in question:

```
	sidero         InfrastructureProvider   https://github.com/talos-systems/sidero/releases/latest/                                     infrastructure-components.yaml
	talos          BootstrapProvider        https://github.com/talos-systems/cluster-api-bootstrap-provider-talos/releases/latest/bootstrap-components.yaml
	talos          ControlPlaneProvider     https://github.com/talos-systems/cluster-api-control-plane-provider-talos/releases/latest/control-plane-components.yaml
```

After I added the following to my `~/.cluster-api/clusterctl.yaml` I was able to install sidero:

```
providers:
  - name: "sidero"
    url: "https://github.com/siderolabs/sidero/releases/latest/infrastructure-components.yaml"
    type: "InfrastructureProvider"
  - name: "talos"
    url: "https://github.com/siderolabs/cluster-api-bootstrap-provider-talos/releases/latest/bootstrap-components.yaml"
    type: "BootstrapProvider"
  - name: "talos"
    url: "https://github.com/siderolabs/cluster-api-control-plane-provider-talos/releases/latest/control-plane-components.yaml"
    type: "ControlPlaneProvider"
```
