### ISSUE TITLE
split `Environment` and boot kernel args

### ISSUE THREAD

**Issue by smira** [siderolabs/sidero#835]
Environment idea is to target the specific Talos version, so it might contain something as simple as: Talos version and arch (default amd64). Every other field might be computed from that version - download URLs, Talos-imposed kernel args.

At the same time there are some platform-specific, Server-specific or ServerClass specific settings like console args or some other hardware-related kernel args (see #834). We could have stored them in a separate resource (?).

**Comment by smira** [comment]
```yaml
spec:
    talosVersion: v1.0.1
    arch: // default amd64
```

--> 

```yaml
status:
   initramfsURL: https://github.com/...
   ready: true
```

```yaml:
spec:
   initramfsUrl:
   vmlinuzUrl:
   kernelArgs: // Talos imposed
```
