### ISSUE TITLE
`BootArguments` resource

### ISSUE THREAD

**Issue by smira** [siderolabs/sidero#836]
`BootArguments` describes boot environment based on MAC address and architectures.

### BootArguments

```yaml
metadata:
  name: dell-console
spec:
   kernelArguments:
      - console=ttyS1
```

### BootArgumentsQualifiers

```yaml
spec:
   bootstrapArgumentRefs:
      - name: dell-console
   qualifiers: # OR on top level, AND on qualifiers
       - arch: amd64
         hardwareAddress: 03:04:0x:*
         subnet: 192.168.0.0/24
         hostname: foo*
         domain: *.bar.baz
   weight: 340 # optional, if needed to resolve conflicts
```

These should be applied to the agent environment as well.

On PXE booting a node, Sidero finds all `BootArguments` which matches the node, sorts them by (`weight`, `name`) and merges them all together. The base arguments are coming from the default agent boot args (if it's an agent boot) or from the Environment (if booting `Server`).
