### ISSUE TITLE
Add baseboard info to server resource

### ISSUE THREAD

**Issue by miragecentury** [siderolabs/sidero#930]
Hi,
I have a Dell C6100 ( 2U 4 Nodes ) and 2 of my node have the same serial number but not the same board Number.
Sidero is not able to distinguish both. 

How can i force the distinguish ?

```
  system:
    family: Server
    manufacturer: Dell
    productName: C6100
    serialNumber: C91S85J
    skuNumber: Unknown
    version: A00
```
